# Generated by Django 6.0.5 on 2026-08-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[("masculino", "Masculino"), ("feminino", "Feminino")],
                        default="masculino",
                        max_length=20,
                    ),
                ),
                ("duracao_minutos", models.IntegerField()),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="BloqueioHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("hora", models.TimeField(verbose_name="Horário bloqueado")),
                (
                    "motivo",
                    models.CharField(blank=True, max_length=200, verbose_name="Motivo"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bloqueio de Horário",
                "verbose_name_plural": "Bloqueios de Horários",
                "ordering": ["data", "hora"],
                "unique_together": {("data", "hora")},
            },
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente_nome",
                    models.CharField(max_length=150, verbose_name="Nome do cliente"),
                ),
                (
                    "cliente_telefone",
                    models.CharField(max_length=20, verbose_name="Telefone"),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de início")),
                ("hora_fim", models.TimeField(verbose_name="Hora de fim")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmado", "Confirmado"),
                            ("cancelado", "Cancelado"),
                            ("concluido", "Concluído"),
                        ],
                        default="confirmado",
                        max_length=20,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos_principal",
                        to="users.servico",
                        verbose_name="Serviço principal",
                    ),
                ),
                (
                    "servico_adicional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos_adicional",
                        to="users.servico",
                        verbose_name="Serviço adicional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["data", "hora_inicio"],
            },
        ),
    ]
